-- =============================================================================
-- 0014_tickets_callbacks.sql
-- Turn review_queue into a workable ticket system with callback capture.
--
-- WHY NOW: Tsunami has no human phone line yet, so a callback ticket is the
-- ONLY escalation path the agent has. Escalation today is apply_flag() firing
-- AFTER the call, which creates a review item with no phone number attached —
-- the caller's number exists only as spoken words inside the transcript, and
-- nobody can work that queue.
--
-- WHY EXTEND review_queue INSTEAD OF A NEW `tickets` TABLE: review_queue is
-- already ~70% of one (reason, details, status, resolved_at, assignee,
-- conversation link, and a working dashboard page with resolve/dismiss/reopen).
-- A parallel table would give the client two inboxes that disagree.
--
-- Safe to re-run.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Ticket columns.
-- -----------------------------------------------------------------------------
alter table review_queue
  -- Human-speakable reference. A UUID is unusable out loud; "ticket ten
  -- forty-two" is what the agent reads back and what the caller quotes.
  add column if not exists ticket_no        bigint generated by default as identity,
  add column if not exists priority         text not null default 'normal',
  -- Denormalized from the conversation so the queue can filter without a join.
  add column if not exists channel          text,
  -- Idempotency key, '<call_sid>:callback'. A retried tool call must not create
  -- a second ticket for the same request.
  add column if not exists external_ref     text,
  add column if not exists callback_number  text,
  -- What the caller actually said: "after 3pm", "any time tomorrow".
  add column if not exists callback_window  text,
  add column if not exists callback_due_at  timestamptz,
  add column if not exists callback_status  text not null default 'none',
  add column if not exists callback_attempts int not null default 0,
  add column if not exists last_attempt_at  timestamptz;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'review_queue_priority_check') then
    alter table review_queue add constraint review_queue_priority_check
      check (priority in ('low','normal','high','urgent'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'review_queue_callback_status_check') then
    alter table review_queue add constraint review_queue_callback_status_check
      check (callback_status in ('none','scheduled','attempted','completed','failed'));
  end if;
end $$;

-- `reason` is text+CHECK, not an enum — 0001 chose that deliberately so new
-- triggers wouldn't need a type migration. Adding a value is therefore a
-- drop-and-recreate of the constraint.
alter table review_queue drop constraint if exists review_queue_reason_check;
alter table review_queue add constraint review_queue_reason_check
  check (reason in ('order_over_24h','abnormal_status','caller_request',
                    'no_order_id','callback_request','other'));

-- The idempotency guard. Partial so the many existing rows with a NULL ref
-- don't collide with each other.
create unique index if not exists uq_review_client_external_ref
  on review_queue (client_id, external_ref) where external_ref is not null;

-- Working the queue = "what's due soonest".
create index if not exists idx_review_callback_due
  on review_queue (client_id, callback_due_at)
  where callback_status in ('scheduled','attempted');

-- -----------------------------------------------------------------------------
-- 2. Activity trail.
-- -----------------------------------------------------------------------------
create table if not exists ticket_notes (
  id         uuid        primary key default gen_random_uuid(),
  ticket_id  uuid        not null references review_queue(id) on delete cascade,
  client_id  uuid        not null references clients(id) on delete cascade,
  -- Matches review_queue.assignee, which references the app's own users table.
  author_id  uuid        references users(id) on delete set null,
  body       text        not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_ticket_notes_ticket
  on ticket_notes (ticket_id, created_at);

alter table ticket_notes enable row level security;

drop policy if exists ticket_notes_tenant on ticket_notes;
create policy ticket_notes_tenant on ticket_notes
  for all using (client_id = current_client_id())
  with check (client_id = current_client_id());

-- -----------------------------------------------------------------------------
-- 3. create_ticket — called by the voice-ticket edge function mid-call.
--
--    Idempotent on (client_id, external_ref), and on a duplicate it returns the
--    EXISTING ticket number rather than silently doing nothing. That matters
--    audibly: the agent reads this number back to the caller, so a retried tool
--    call must produce the SAME number, not a failure or a second ticket.
--    (The silent `on conflict do nothing` pattern is what made agent replies
--    vanish from the dashboard on the email side — same trap, avoided here.)
-- -----------------------------------------------------------------------------
create or replace function create_ticket(
  p_client_id       uuid,
  p_conversation_id uuid    default null,
  p_reason          text    default 'callback_request',
  p_details         text    default null,
  p_priority        text    default 'normal',
  p_callback_number text    default null,
  p_callback_window text    default null,
  p_external_ref    text    default null,
  p_channel         text    default 'voice',
  p_due_at          timestamptz default null
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_id        uuid;
  v_no        bigint;
  v_due       timestamptz;
  v_ref       text := nullif(trim(coalesce(p_external_ref, '')), '');
  v_duplicate boolean := false;
begin
  if p_client_id is null then
    return jsonb_build_object('ok', false, 'error', 'client_id is required');
  end if;
  if not exists (select 1 from clients where id = p_client_id) then
    return jsonb_build_object('ok', false, 'error', 'unknown_client');
  end if;

  -- Simple SLA placeholder. NOT business-hours aware yet — Tsunami's
  -- business_hours is still {} — so the agent must promise only "the next
  -- business window", never a specific time. Callers can pass p_due_at.
  v_due := coalesce(p_due_at, now() + interval '4 hours');

  insert into review_queue (
    client_id, conversation_id, reason, details, status, priority, channel,
    external_ref, callback_number, callback_window, callback_due_at,
    callback_status
  )
  values (
    p_client_id, p_conversation_id, p_reason, p_details, 'pending',
    coalesce(p_priority, 'normal'), p_channel,
    v_ref,
    nullif(trim(coalesce(p_callback_number, '')), ''),
    nullif(trim(coalesce(p_callback_window, '')), ''),
    v_due,
    case when nullif(trim(coalesce(p_callback_number, '')), '') is null
         then 'none' else 'scheduled' end
  )
  on conflict (client_id, external_ref) where external_ref is not null
  do nothing
  returning id, ticket_no into v_id, v_no;

  -- Conflict -> hand back the ticket that already exists, so the agent reads
  -- the caller the same number it read them the first time.
  if v_id is null and v_ref is not null then
    select id, ticket_no into v_id, v_no
    from review_queue
    where client_id = p_client_id and external_ref = v_ref;
    v_duplicate := v_id is not null;
  end if;

  if v_id is null then
    return jsonb_build_object('ok', false, 'error', 'insert_failed');
  end if;

  select callback_due_at into v_due from review_queue where id = v_id;

  return jsonb_build_object(
    'ok',              true,
    'ticket_id',       v_id,
    'ticket_no',       v_no,
    'duplicate',       v_duplicate,
    'callback_due_at', v_due
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- 4. record_callback_attempt — dashboard action when a human works the queue.
-- -----------------------------------------------------------------------------
create or replace function record_callback_attempt(
  p_ticket_id uuid,
  p_outcome   text,          -- 'attempted' | 'completed' | 'failed'
  p_note      text default null,
  p_author_id uuid default null
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_client uuid;
  v_att    int;
begin
  select client_id into v_client from review_queue where id = p_ticket_id;
  if v_client is null then
    return jsonb_build_object('ok', false, 'error', 'unknown_ticket');
  end if;
  if p_outcome not in ('attempted','completed','failed') then
    return jsonb_build_object('ok', false, 'error', 'bad_outcome');
  end if;

  update review_queue
     set callback_status   = p_outcome,
         callback_attempts = callback_attempts + 1,
         last_attempt_at   = now(),
         -- A completed callback closes the ticket; the others leave it open.
         status            = case when p_outcome = 'completed' then 'resolved' else status end,
         resolved_at       = case when p_outcome = 'completed' then now() else resolved_at end
   where id = p_ticket_id
   returning callback_attempts into v_att;

  if p_note is not null and trim(p_note) <> '' then
    insert into ticket_notes (ticket_id, client_id, author_id, body)
    values (p_ticket_id, v_client, p_author_id, p_note);
  end if;

  return jsonb_build_object('ok', true, 'attempts', v_att, 'outcome', p_outcome);
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. Dashboard view: the callback work queue, soonest first.
--    security_invoker is MANDATORY — 0001's default privileges auto-grant
--    `authenticated` on every new table AND view, and a plain view would run
--    with the owner's rights and bypass review_queue's RLS entirely.
-- -----------------------------------------------------------------------------
create or replace view callbacks_due with (security_invoker = true) as
select
  r.id,
  r.client_id,
  r.ticket_no,
  r.priority,
  r.status,
  r.callback_number,
  r.callback_window,
  r.callback_due_at,
  r.callback_status,
  r.callback_attempts,
  r.details,
  r.created_at,
  c.customer_name,
  c.order_number,
  c.id as conversation_id,
  (r.callback_due_at < now()) as overdue
from review_queue r
left join conversations c on c.id = r.conversation_id
where r.callback_status in ('scheduled','attempted')
  and r.status = 'pending';

-- -----------------------------------------------------------------------------
-- 6. Grants — service_role for the RPCs; the views/tables rely on RLS.
-- -----------------------------------------------------------------------------
revoke execute on function create_ticket(uuid, uuid, text, text, text, text, text, text, text, timestamptz) from public;
grant  execute on function create_ticket(uuid, uuid, text, text, text, text, text, text, text, timestamptz) to service_role;

revoke execute on function record_callback_attempt(uuid, text, text, uuid) from public;
grant  execute on function record_callback_attempt(uuid, text, text, uuid) to authenticated, service_role;

grant select on callbacks_due to authenticated, service_role;
grant select, insert on ticket_notes to authenticated, service_role;

comment on column review_queue.ticket_no is
  'Human-speakable reference the voice agent reads back to the caller.';
comment on column review_queue.external_ref is
  'Idempotency key, typically "<call_sid>:callback". Unique per client.';

-- End of 0014.
